### ISSUE TITLE
Use hash instead of $_SERVER['REMOTE_ADDR']

### ISSUE THREAD

**Issue by job** [cottow/6paster#17]
No real need to store actual IP addresses, one could store hashes of `$_SERVER['REMOTE_ADDR']` instead to help enforce a rate limiter

**Comment by cottow** [comment]
Fixed in https://github.com/cottow/6paster/commit/4e575e5fdf180532b2a75ebe7db68f51fa822ba3#diff-2fd41bae20dd4e0eb8823422c2781843
